import { zenPulseCues } from './palettes';
import type { SoundStep, SoundType } from './types';

const ZEN_PULSE_VOLUME = .68;
export function createCooldownGate() { const playedAt = new Map<SoundType, number>(); return (type: SoundType, now: number, cooldown: number) => { const previous = playedAt.get(type) ?? -Infinity; if (now - previous < cooldown) return false; playedAt.set(type, now); return true; }; }
type WebkitWindow = Window & { webkitAudioContext?: typeof AudioContext };

class ZenSoundEngine {
  private context: AudioContext | null = null; private master: GainNode | null = null; private allowed = createCooldownGate(); private unlocked = false;
  private getContext() { if (typeof window === 'undefined') return null; if (!this.context) { const Context = window.AudioContext || (window as WebkitWindow).webkitAudioContext; if (!Context) return null; this.context = new Context(); this.master = this.context.createGain(); this.master.gain.value = ZEN_PULSE_VOLUME; this.master.connect(this.context.destination); } return this.context; }
  unlock() { if (this.unlocked) return; const context = this.getContext(); if (!context) return; void context.resume(); const buffer = context.createBuffer(1, 1, 22050); const source = context.createBufferSource(); source.buffer = buffer; source.connect(this.master ?? context.destination); source.start(); this.unlocked = true; }
  play(type: SoundType) { const context = this.getContext(); const output = this.master; if (!context || !output) return; const definition = zenPulseCues[type]; if (!this.allowed(type, performance.now(), definition.cooldown)) return; if (context.state === 'suspended') void context.resume(); definition.steps.forEach(step => this.schedule(context, output, step)); }
  private schedule(context: AudioContext, output: AudioNode, step: SoundStep) { const start = context.currentTime + (step.at ?? 0); const gain = context.createGain(); const filter = context.createBiquadFilter(); const panner = typeof context.createStereoPanner === 'function' ? context.createStereoPanner() : null; filter.type = 'lowpass'; filter.frequency.setValueAtTime(step.filter ?? 4800, start); if (panner) panner.pan.setValueAtTime(step.pan ?? 0, start); gain.gain.setValueAtTime(.0001, start); gain.gain.exponentialRampToValueAtTime(Math.max(.0002, step.gain), start + (step.attack ?? Math.min(.012, step.duration / 4))); gain.gain.exponentialRampToValueAtTime(.0001, start + step.duration); gain.connect(filter); filter.connect(panner ?? output); panner?.connect(output); const release = () => { gain.disconnect(); filter.disconnect(); panner?.disconnect(); }; if (step.wave === 'noise') { const frames = Math.max(1, Math.floor(context.sampleRate * step.duration)); const buffer = context.createBuffer(1, frames, context.sampleRate); const data = buffer.getChannelData(0); for (let i = 0; i < frames; i += 1) data[i] = Math.random() * 2 - 1; const noise = context.createBufferSource(); noise.buffer = buffer; noise.connect(gain); noise.onended = () => { noise.disconnect(); release(); }; noise.start(start); noise.stop(start + step.duration); return; } const oscillator = context.createOscillator(); oscillator.type = step.wave ?? 'sine'; oscillator.frequency.setValueAtTime(step.frequency, start); if (step.toFrequency) oscillator.frequency.exponentialRampToValueAtTime(Math.max(20, step.toFrequency), start + step.duration); oscillator.connect(gain); oscillator.onended = () => { oscillator.disconnect(); release(); }; oscillator.start(start); oscillator.stop(start + step.duration); }
}
export const soundEngine = new ZenSoundEngine();
